### ISSUE TITLE
Sporadical failure when determining elementary version to install

### ISSUE THREAD

**Issue by volodymyr-mykhailyk** [elementary-data/run-elementary-action#8]
When we run elementary using github action provided we periodically (one out of 10-20 runs) receive such error:
```
Failed to get Elementary dbt package version: {'returncode': 1, 'cmd': ['dbt', '--log-format', 'json', 'run-operation', 'get_elementary_dbt_pkg_version', '--project-dir', '/edr_stager_dbt_project'], 'output': b'{"data": {"log_version": 3, "version": "=1.6.3"}, "info": {"category": "", "code": "A001", "extra": {}, "invocation_id": "29e676ca-7e0b-4303-8004-5073fc4ffa93", "level": "info", "msg": "Running with dbt=1.6.3", "name": "MainReportVersion", "pid": 53, "thread": "MainThread", "ts": "2023-09-22T05:05:00.163150Z"}}\n{"data": {"profile_name": "elementary", "target_name": "default"}, "info": {"category": "", "code": "A005", "extra": {}, "invocation_id": "29e676ca-7e0b-4303-8004-5073fc4ffa93", "level": "info", "msg": "target not specified in profile \'elementary\', using \'default\'", "name": "MissingProfileTarget", "pid": 53, "thread": "MainThread", "ts": "2023-09-22T05:05:00.169196Z"}}\n{"data": {"adapter_name": "snowflake", "adapter_version": "=1.6.2"}, "info": {"category": "", "code": "E034", "extra": {}, "invocation_id": "29e676ca-7e0b-4303-8004-5073fc4ffa93", "level": "info", "msg": "Registered adapter: snowflake=1.6.2", "name": "AdapterRegistered", "pid": 53, "thread": "MainThread", "ts": "2023-09-22T05:05:00.561663Z"}}\n{"data": {"reason": "saved manifest not found. Starting full parse."}, "info": {"category": "", "code": "I024", "extra": {}, "invocation_id": "29e676ca-7e0b-4303-8004-5073fc4ffa93", "level": "info", "msg": "Unable to do partial parsing because saved manifest not found. Starting full parse.", "name": "UnableToPartialParse", "pid": 53, "thread": "MainThread", "ts": "2023-09-22T05:05:00.579243Z"}}\n{"data": {"stat_line": "0 sources, 0 exposures, 0 metrics, 378 macros, 0 groups, 0 semantic models"}, "info": {"category": "", "code": "W006", "extra": {}, "invocation_id": "29e676ca-7e0b-4303-8004-5073fc4ffa93", "level": "info", "msg": "Found 0 sources, 0 exposures, 0 metrics, 378 macros, 0 groups, 0 semantic models", "name": "FoundStats", "pid": 53, "thread": "MainThread", "ts": "2023-09-22T05:05:01.880693Z"}}\n{"data": {"exc": "Compilation Error\\n  agate.table.Table object has no element 0"}, "info": {"category": "", "code": "Q001", "extra": {}, "invocation_id": "29e676ca-7e0b-4303-8004-5073fc4ffa93", "level": "error", "msg": "Encountered an error while running operation: Compilation Error\\n  agate.table.Table object has no element 0", "name": "RunningOperationCaughtError", "pid": 53, "thread": "MainThread", "ts": "2023-09-22T05:05:03.175720Z"}}\n', 'stderr': b''}
Traceback (most recent call last):
  File "/entrypoint.py", line 134, in <module>
    main()
  File "/entrypoint.py", line 125, in main
    install_edr(args.adapter, args.project_dir)
  File "/entrypoint.py", line 44, in install_edr
    command_results = subprocess.run(
  File "/usr/local/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['dbt', '--log-format', 'json', 'run-operation', 'get_elementary_dbt_pkg_version', '--project-dir', '/edr_stager_dbt_project']' returned non-zero exit status 1.
```

From my understanding GitHub actions calls for [elementary macros](https://github.com/elementary-data/elementary/blob/5d39b9f1a10a8fe6d37010400e96ed634f455092/elementary/monitor/dbt_project/macros/get_elementary_dbt_pkg_version.sql) `get_elementary_dbt_pkg_version` that prints all packages/versions used by dbt project.

Could you please help me understand why it fails? If not, do you think it will be appropriate to allow specifying the elementary version via action parameter and skip this step altogether?

**Comment by mjrulesamrat** [comment]
We are also facing the same issue with elementary github action.

**Comment by mjrulesamrat** [comment]
@volodymyr-mykhailyk Which data warehouse are you using? I see that at databricks implementation is missing inside the macros [get_elementary_dbt_pkg_version](https://github.com/elementary-data/run-elementary-action/blob/main/edr_stager_dbt_project/macros/get_elementary_dbt_pkg_version.sql#L20)

**Comment by volodymyr-mykhailyk** [comment]
> @volodymyr-mykhailyk Which data warehouse are you using? I see that at databricks implementation is missing inside the macros [get_elementary_dbt_pkg_version](https://github.com/elementary-data/run-elementary-action/blob/main/edr_stager_dbt_project/macros/get_elementary_dbt_pkg_version.sql#L20)

We are using snowflake.

**Comment by volodymyr-mykhailyk** [comment]
In our case, the root cause was the cleaning of table `dbt_invocations` every day on full data refresh. I will close the issue as it is not the project issue but the incorrect setup on our end. 

Question about alternative ways to provide an elementary version might still be valid.
